version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      - INSTANCE_DOMAIN=${INSTANCE_DOMAIN}
      - INSTANCE_PROTOCOL=${INSTANCE_PROTOCOL}
      - INTERACTIVE_KEY=${INTERACTIVE_KEY}
      - INTERACTIVE_SECRET=${INTERACTIVE_SECRET}
      - API_KEY=${API_KEY}
      - IMG_ASSET_ID=${IMG_ASSET_ID}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
