# No clear secrets in git. Ciphertext only; the in-cluster sealed-secrets
# controller unseals it into Secret vpet0-secrets (envFrom). Sealed (strict
# scope) against the dev cluster cert for namespace sdk-apps-dev.
# Re-seal:  kubeseal --cert sealed-secrets-dev.pem --format yaml \
#             --namespace sdk-apps-dev --name vpet0-secrets < raw-secret.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vpet0-secrets
  namespace: sdk-apps-dev
spec:
  encryptedData:
    API_KEY: AgA0EjdL/fikJjYkC3QqE2100iaAN+PbFj46+POSPHIbQjIEhEGRTdUqub4s63CMJJRQbiRAxYLom83CrqrmJGh9yaXjTiSA89fbdR13y5DF87pUfhC/pgqrb1TnuKP1N6TXN+OAnbhUnf5AvXui/7qSg9Wc1aN0ViWdaSkkyREnDM8estqGG6DNFrHfxo4OYbAivxPAzIbZW+96mXkYQ5AWI9uhBrhMFn6AN2x9oXg3MlQyc6k3B5rlav/UfL8O0Nn5jdjPus/QaieZj0N/rPOJaiRc39ej/lWxO+OoDyiKsElJdkoqg4PMSYs6dlmnJ6OVqTYJMqSPb3FlwSFNY/XpDwJZgaM34Xg9u64JZZFuT917HfQo2xCiRygLPLfyCJ05dQPoDVgyEm69Ppi+0XH275HI/ISeqyd2V+MmaZS+SxBfr0WEwYcLh3F04+qS/hSup7FVfPAcQR2RlEaNp4s3sYLoDslurbQaznypElssRA2/lqzpdw2bBkU0Ny6h97Qhh5ZLL0mVrywDCEc6lu/0VZ1ZeRTDxpOZVv//JVFGhhVb4eZpzU5mSYockdiK5YErKfIT9ytNZeHnV01lIdmILLNvsrkH76AGPLVwoLcu6I/ubvMkCj6TZNEhmwxp41M9JdKrfP+4kv1HhzU+21vxyoeJEE7aHnLf3toLjJcj1gQCihvHDN4dW9EIa9WpWRnFEN2edqfDq9eLJ1o7uiTFGWoD5zvCRy6a6yTCSQXNsEywDfk=
    INTERACTIVE_SECRET: AgCfQwyxV+Lhmbhf2KEb7liDxev1+DNybF+ehGozMIVhA8WDJowBodLCfTmdnvSlhyWPnwKVAt68VKwKozcdk3DG9TplqRLRt0CSq4xJZX6JRftyWCAkIvDO9XBP+rCw+q/dZ2F9stg1FA/YiVs+sqC6BcRKONpFbw8zHXK1AEbw46UwiPjn1eErGOiYnwlXq8/Zprfxx7X4zg871b0jBh6taJhL6e7as48fO4wKzGFAcmB2UE647FWGDCLf/soQPykAzaNXi0w71KM5MYTXVNIaNJ2H8qxmbooVxD3WLkYUSTvGTKKMrWJNrFBlXIKKiRcuUvw0so7+erhWq4Cs2TCBgFZze+D9dGeTYYL+ZiUGrmXaZd328WeJocnrar6jHEwoMHcNZWqMBOUMXztirLn3e0p/sND4pjmEXhASgs6o6iQykBmiNYgjsaWHV9KBNVIiOrAxWLpCDA6SWk/oHQLdQCLP1lGIM+b6MG6pCbW1eNTWsKzVhfDyefl7aQpY7ZN+WvfL9/BTB/0asfBnFyzmmK278GwK6UhmH7aFHLztNY6iOi6DzwpL37jjampfTwP23IDYczMfEQG0qOMvmdynspX2Isgu1Oqlb2XcoKie5Ea9l0RbvVCRiXB5GsqSR8c6sUycPPXU0g9R/emE59lj62xkXD3UIUSmE1o3NJfR0Cxx04NCYZQw+0J3dX4VS4UzPbu3UoUZL4xUjXIBTW71lx6t38OJdBT6u6/8DbkkoZOskfx3p6VPzXAs7A9fTFM=
  template:
    metadata:
      name: vpet0-secrets
      namespace: sdk-apps-dev
    type: Opaque
