apiVersion: v1
kind: Service
metadata:
  name: stg-vpet0
  labels:
    app.kubernetes.io/name: stg-vpet0
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: stg-vpet0
  ports:
    - name: http
      port: 80
      targetPort: http
