apiVersion: v1
kind: ConfigMap
metadata:
  name: stg-vpet0-config
  labels:
    app.kubernetes.io/name: stg-vpet0
data:
  BROWSER: "none"
  IMG_ASSET_ID: "webImageAsset"
  INSTANCE_DOMAIN: "api-stage.topia.io"
  INSTANCE_PROTOCOL: "https"
  INTERACTIVE_KEY: "88gD1v7gYPrmzbCilhsP"
  IS_LOCALHOST: "true"
  NODE_ENV: "production"
  PORT: "3000"
  REACT_APP_API_URL: "vpet-dev-topia.topia-rtsdk.com"
  REACT_APP_LOCALHOST: "true"
  S3_BUCKET: "sdk-virtual-pet"
