# No clear secrets in git. Ciphertext only; the in-cluster sealed-secrets
# controller unseals it into Secret stg-vpet0-secrets (envFrom). Sealed (strict
# scope) against the dev cluster cert for namespace sdk-apps-stg.
# Re-seal:  kubeseal --cert sealed-secrets-dev.pem --format yaml \
#             --namespace sdk-apps-stg --name stg-vpet0-secrets < raw-secret.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stg-vpet0-secrets
  namespace: sdk-apps-stg
spec:
  encryptedData:
    API_KEY: AgCsJKK5eP2nzmtfjEKquI9ZSmNIhweAfu8jv3M/NLh5AOdCyure67GY0AOpEXMTWvYl/A7sw+O0P9vGMVUS1Eg/BKOdp74r5dSSnHunruTV6RMNG7MBGhrRs6/fzaFtr3jUccBKgsYqaIzZvZ999pYBF+wiCCLuRbUdwkJNG2gj44vi17zM73CpVHG64mVW7iyLHxQfOSgOX1/qB8uU4HKuZS0xusxf0r1BZhh0UsKmp00SmAwE89Z1q9Kl1RTZF+4cp/MY+2AN0mGB7GMwo8uEV/Fy24kt1cKUIgmeG3+Yc9yUM+6kRTdgPtdLu6PjOt4xKxLWEIKP0o+O6sW6Q7AjE/c+fu4z/vHuVG43GQimpmDbrquHwILcwBuLcmLgCIv/EqaMzCkQ2U4hDF8rCQgkz3r2TYTRdcizqMYnhIPVIcMnJIHwOXxhLLbM+zRK/sDCMUntn57GknFbhgZRNzrBQv0vmCe4cz0jZjaDC6AmeWkjrZ6udJYValJJXupxQXn8OnNku4wU1z+MontSW0uwwvhzTrEb1jvlOYBDc8SaZXWNm+JKMxxW5ZSiiq3PcXg4X8F78dQp9X497iuKnRYVkvr/7JNH403HqJx4TkYfaF7Ge4FK8yBV7/rKeZYhTCC1RmEb4b+ZPxJ34+IWoGBBpWGOZmTi3WMWhb2DPb00TFgvk/tjIohnspUHvsPSTmulf0jhKxUUyCdgKda9GhTY3wCAmEmAhdT17+mvBrcKnJdBIP0=
    INTERACTIVE_SECRET: AgCRS5abbKvpBOs8w63dMZ00sDnauttEFT+QTumK5Wcd0BqZv7SP6MQLPeFp/hWDxI8doQU8CgSNQa3uatIlOqzqIFsI8lBVZazxDg6It7rNHjRHm/Hz6GELdkIJJUAKcZpPKmGczifN+t9kftKbxiWQayCndGIZBl5FDmej8DNHhpcRv/OBJI5c3XNWF41CPfVLBXsDRI/X7yPgMUeAgqwjx7XjDdWlKuOPEbdWcsfyLO4EmKia7ygg1EoZbd1tTbieUrGVtOA2w1yS6Asc/aq3ZGZ5lEKQqkleXLTSBD1egDNBz3AS325S8nlUdqQaFGdfgS3/IpJ+RZU/alNmLYdPTSQzQvI8RgKbFo1h8GOXe6AsrfWOXcTu6s5TiRjp08hYJ7/wqiWi2hnMzNajywm6H7BZQvukpZVrmlZkrCp5+y+KinDTIc2etfzMojOOldnAsZkGkJSZKsVHJnBImNWovZhew8Wu7uE/2gvmt3DP+jaUC1CGIuvcXmIWGj01okoZuTO5puPWR0aq3Zcbyfnll3lqJqAlUMijKK1eQK+DWHWHBInxH5/P4HGmLzyrs7AurGpDzBqyvRHNuFTlErrXB1hhglaR6bRso3+PkMbdIfLsf6XydUVN4Ih7QMbQFTKmkCsnHAG07PnZZQlkhHFUeox1gi/oW5BcSJ+QlVXdD3mKZeo4ZVbxXoT+QJScixDfgydufZw6tpMdkfbRFDFQXgJZLQC3JZwXjnhnMXwxES0WA98LRyXZMWqmv4yhLdY=
  template:
    metadata:
      name: stg-vpet0-secrets
      namespace: sdk-apps-stg
    type: Opaque
